### ISSUE TITLE
month must be in 1..12?

### ISSUE THREAD

**Issue by stall7** [sourceperl/rpi.rtc#1]
`>>> rtc.read_datetime()`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/pyRPiRTC-0.0.2-py3.4.egg/pyRPiRTC.py", line 151, in read_datetime
ValueError: month must be in 1..12

what's  problem in thie error?

**Comment by sqasm** [comment]
same here...
Traceback (most recent call last):
File "", line 1, in
File "/usr/local/lib/python3.4/dist-packages/pyRPiRTC-0.0.2-py3.4.egg/pyRPiRTC.py", line 151, in read_datetime
ValueError: month must be in 1..12

**Comment by sourceperl** [comment]
Hi,

I have the same issue when i launch "ds1302_get_utc" without RTC clock connect to Pi.

It's probably a wiring issue or a problem with the RTC chip. 

I will try to reproduce this bug with a Pi3 and another ds1302.

Have a nice day.

**Comment by sourceperl** [comment]
I check with a new Pi 3 B+ and 2 ds1302, all seem ok.

I add an explicit error message instead of the default Python ValueError except in commit 1972cf8.
