### ISSUE TITLE
ValueError: month must be in 1..12

### ISSUE THREAD

**Issue by sqasm** [sourceperl/rpi.rtc#2]
pi@rpi:~/rpi.rtc-master $ ds1302_set_utc
Traceback (most recent call last):
  File "/usr/local/bin/ds1302_set_utc", line 4, in <module>
    __import__('pkg_resources').run_script('pyRPiRTC==0.0.2', 'ds1302_set_utc')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1501, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/pyRPiRTC-0.0.2-py3.5.egg/EGG-INFO/scripts/ds1302_set_utc", line 17, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pyRPiRTC-0.0.2-py3.5.egg/pyRPiRTC.py", line 151, in read_datetime
ValueError: month must be in 1..12

**Comment by sourceperl** [comment]
Same as #1.
